#PBS -l walltime=1:00
#PBS -l nodes=2:ppn=16
#PBS -q debug16core

FN="scratch/CSCE3213/smallfile.fastq";
PC=48;
                                        # copy PBS_NODEFILE to current directory
cd $PBS_O_WORKDIR                       # so it is available to all nodes
cp $PBS_NODEFILE nodefile
for n in `uniq $PBS_NODEFILE`; do       # ssh to each job node and run ./nodecode.sh
   ssh $n "cd $PBS_O_WORKDIR; ./nodesort.sh nodefile" &
done;

for n in `uniq $PBS_NODEFILE`; do       # wait for all nodes to finish
   while [ `ls $n.finished|wc -l` -eq 0 ]; do
       sleep 1;
   done;
done

sort -m -n -k1 piece.*.sorted > sorted2.$2.txt;
echo "Total lines in sorted document is $(wc -l sorted2.$2.txt)"
rm piece.*
